INSERT INTO "Productos" (id, nombre, gramajes, categoria) VALUES
('C01', 'Acacia de la India',       ARRAY[10],         'HIERBAS'),
('C02', 'Acento',                   ARRAY[500],        'CONDIMENTO'),
('C03', 'Ajo',                      ARRAY[30,250,500], 'CONDIMENTO'),
('C04', 'Albahaca',                 ARRAY[10],         'HIERBAS'),
('C05', 'Anís Estrellado',           ARRAY[10],        'REPOSTERIA'),
('C06', 'Apio',                     ARRAY[10],         'HIERBAS'),
('C07', 'Bicarbonato de Soda',      ARRAY[30,500],     'REPOSTERIA'),
('C08', 'Boldo',                    ARRAY[10],         'HIERBAS'),
('C09', 'Caldo de Gallina',         ARRAY[500],        'CONDIMENTO'),
('C10', 'Caléndula',                ARRAY[5,10],       'HIERBAS'),
('C11', 'Canela en Astillas',       ARRAY[8,15,30],    'REPOSTERIA'),
('C12', 'Canela Molida',            ARRAY[20,40,500],  'REPOSTERIA'),
('C13', 'Chía',                     ARRAY[50,100,500], 'REPOSTERIA'),
('C14', 'Cidron',                   ARRAY[10],         'HIERBAS'),
('C15', 'Clavos de Olor Entero',    ARRAY[5,500],      'REPOSTERIA'),
('C16', 'Clavos de Olor Molido',    ARRAY[5,500],      'REPOSTERIA'),
('C17', 'Coco',                     ARRAY[20,50,100],  'REPOSTERIA'),
('C18', 'Color',                    ARRAY[20,50,100],  'CONDIMENTO'),
('C19', 'Color',                    ARRAY[500],        'CONDIMENTO'),
('C20', 'Comino Entero',            ARRAY[20,50,100],  'CONDIMENTO'),
('C21', 'Comino Molido',            ARRAY[500],        'CONDIMENTO'),
('C22', 'Cúrcuma',                  ARRAY[30],         'CONDIMENTO'),
('C23', 'Curry',                    ARRAY[20,500],     'CONDIMENTO'),
('C24', 'Estevia',                  ARRAY[10],         'HIERBAS'),
('C25', 'Finas Hierbas',            ARRAY[20,500],     'CONDIMENTO'),
('C26', 'Flor de Jamaica',          ARRAY[10],         'HIERBAS'),
('C27', 'Guasca',                   ARRAY[10],         'HIERBAS'),
('C28', 'Jengibre',                 ARRAY[30],         'HIERBAS'),
('C29', 'Laurel Hoja',              ARRAY[5,500],      'CONDIMENTO'),
('C30', 'Laurel Molido',            ARRAY[20,500],     'CONDIMENTO'),
('C31', 'Limoncillo',               ARRAY[10],         'HIERBAS'),
('C32', 'Linaza Entera',            ARRAY[50,500],     'REPOSTERIA'),
('C33', 'Linaza Molida',            ARRAY[50,500],     'REPOSTERIA'),
('C34', 'Manzanilla',               ARRAY[5,10],       'HIERBAS'),
('C35', 'Menta',                    ARRAY[10],         'HIERBAS'),
('C36', 'Moringa',                  ARRAY[10],         'HIERBAS'),
('C37', 'Nueces del Brasil',        ARRAY[50,100,500], 'REPOSTERIA'),
('C38', 'Nuez Moscada Entera',      ARRAY[10,500],     'REPOSTERIA'),
('C39', 'Nuez Moscada Molida',      ARRAY[20,500],     'REPOSTERIA'),
('C40', 'Orégano Molido',           ARRAY[20,50,100],  'CONDIMENTO'),
('C41', 'Orégano Picado',           ARRAY[10,500],     'CONDIMENTO'),
('C42', 'Paprika',                  ARRAY[20,500],     'CONDIMENTO'),
('C43', 'Pasas',                    ARRAY[50,100],     'REPOSTERIA'),
('C44', 'Perejil',                  ARRAY[10],         'HIERBAS'),
('C45', 'Pimienta Entera',          ARRAY[20,500],     'CONDIMENTO'),
('C46', 'Pimienta Molida',          ARRAY[20,500],     'CONDIMENTO'),
('C47', 'Romero',                   ARRAY[10],         'HIERBAS'),
('C48', 'Sal de Ajo',               ARRAY[20,500],     'CONDIMENTO'),
('C49', 'Sazón',                    ARRAY[20,50,100,500], 'CONDIMENTO'),
('C50', 'Té Verde',                 ARRAY[10],         'HIERBAS'),
('C51', 'Tomillo Molido',           ARRAY[20,500],     'CONDIMENTO'),
('C52', 'Tomillo Picado',           ARRAY[10,500],     'CONDIMENTO'),
('C53', 'Toronjil',                 ARRAY[10],         'HIERBAS'),
('C54', 'Hierbabuena',              ARRAY[10],         'HIERBAS');

INSERT INTO "Empleados" (nombre) VALUES
('Maria Isabel Duque Betancourth'),
('Jhon Jaime Lopez Garcia'),
('Diana Carolina Atehortua');

